name: cmcc-rxn
channels:
  - rdkit
  - pytorch
  - openeye
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - "ase"
  - "rdkit"
  - "matplotlib"
  - "ipykernel"
  - "pytorch==2.3.0"
  - "pip"
  - pip:
    - "torch_cluster"
    - "mccoygroup-mcutils"
    - "mccoygroup-psience"
    - "chython"
    - "chytorch"
    - "chytorch-rxnmap"
    - "git+https://github.com/isayevlab/AIMNet2"
