name: cmcc-rxn-uma
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11,<3.14
  - pip
  - jupyterlab
  - pip:
      - pysisyphus
      - orjson
      - mccoygroup-mcutils
      - mccoygroup-psience
      - rdkit
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.8.0
      - --find-links https://data.pyg.org/whl/torch-2.8.0+cpu.html
      - torch-cluster
      - torch-scatter
      - fairchem-core>2.0
      - git+https://github.com/Center-for-Mechanical-Control-of-Chem/cmcc-reactions.git
