name: cmcc-rxn-mace
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - pip
  - jupyterlab
  - pip:
      - pysisyphus
      - mccoygroup-mcutils
      - mccoygroup-psience
      - rdkit
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.8.0
      - --find-links https://data.pyg.org/whl/torch-2.8.0+cpu.html
      - torch_geometric
      - mace-torch
      - git+https://github.com/Center-for-Mechanical-Control-of-Chem/cmcc-reactions.git
