name: cmcc-rxn
channels:
  - rdkit
  - pytorch
  - openeye
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - "ase",
  - "rdkit",
  - "matplotlib",
  - "ipykernel"
  - pip:
    - "torch==2.3.0"
    - "mccoygroup-mcutils"
#    - "torch_cluster=",
#    - "git+https://github.com/isayevlab/AIMNet2"